import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, Download, Film, LoaderCircle, Search, Sparkles, Upload, X } from 'lucide-react';
import type { ModuleState } from '../shared/types';
import type { MediaEvent, MediaRanking, MediaSummary } from '../shared/media';
import './media.css';
import { MediaDevices } from './MediaDevices';
import { formatMediaDuration } from '../shared/media-time';
import { MediaWatchTime } from './MediaWatchTime';
import { MediaTimeMetric } from './MediaTimeMetric';
import { MediaChannels } from './MediaChannels';
const ranges=[['28d','近 28 天'],['90d','近 90 天'],['365d','近一年'],['all','全部紀錄']] as const;
const names:Record<string,string>={overview:'觀看概況',channels:'頻道探索與分類',topics:'興趣主題',history:'觀看紀錄'};
const number=(value:number)=>value.toLocaleString('zh-TW');
const date=(value:string|null)=>value?new Date(value).toLocaleDateString('zh-TW',{timeZone:'Asia/Taipei'}):'尚無紀錄';
async function mediaApi<T>(path:string,init:RequestInit={}):Promise<T>{
  const response=await fetch(`/api/v1/media/${path}`,{credentials:'same-origin',cache:'no-store',...init});
  if(!(response.headers.get('content-type')??'').includes('application/json'))throw new Error('目前無法讀取影音資料，請確認登入與主機連線。');
  const body=await response.json();if(!response.ok)throw new Error(body.error??'操作未完成。');return body;
}
export function MediaPage({state,update,openCatalog}:{state:ModuleState|undefined;update:(state:ModuleState)=>Promise<void>;openCatalog:()=>void}){
  const [range,setRange]=useState('90d'),[summary,setSummary]=useState<MediaSummary|null>(null),[history,setHistory]=useState<MediaEvent[]>([]),[hasMore,setHasMore]=useState(false);
  const [q,setQ]=useState(''),[page,setPage]=useState(0),[revision,setRevision]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[deleting,setDeleting]=useState(false),[confirmation,setConfirmation]=useState('');
  const [exportPart,setExportPart]=useState(1);
  useEffect(()=>{if(summary&&exportPart>Math.max(1,Math.ceil(summary.total/5000)))setExportPart(1);},[summary,exportPart]);
  const upload=useRef<HTMLInputElement>(null);
  useEffect(()=>{setPage(0);},[range,q]);
  useEffect(()=>{
    if(!state?.enabled)return;const controller=new AbortController();setError('');
    void mediaApi<MediaSummary>(`summary?range=${range}`,{signal:controller.signal}).then(setSummary).catch(err=>{if(!controller.signal.aborted)setError(err.message);});
    return()=>controller.abort();
  },[range,revision,state?.enabled]);
  useEffect(()=>{
    if(!state?.enabled)return;const controller=new AbortController();
    const timer=window.setTimeout(()=>{void mediaApi<{items:MediaEvent[];hasMore:boolean}>(`history?range=${range}&q=${encodeURIComponent(q)}&page=${page}`,{signal:controller.signal}).then(result=>{setHistory(result.items);setHasMore(result.hasMore);}).catch(err=>{if(!controller.signal.aborted)setError(err.message);});},200);
    return()=>{window.clearTimeout(timer);controller.abort();};
  },[range,q,page,revision,state?.enabled]);
  async function importFile(file?:File){
    if(!file)return;if(file.size>50*1024*1024){setError('檔案超過 50 MB，請分批匯出。');return;}setBusy(true);setError('');setNotice('正在匯入；大型紀錄可能需要稍候。');
    try{const result=await mediaApi<{inserted:number;skipped:number;repeated:boolean;source:string}>('import',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});setNotice(result.repeated?'這份檔案已匯入，不會重複新增。':`${result.source} 匯入完成：新增 ${number(result.inserted)} 筆；重複、取代或無效紀錄 ${number(result.skipped)} 筆。`);setRange('all');setRevision(v=>v+1);}catch(err){setError((err as Error).message);setNotice('');}finally{setBusy(false);if(upload.current)upload.current.value='';}
  }
  async function classify(){setBusy(true);setError('');setNotice('AI 正在並行整理尚未分類的影片…');try{const result=await mediaApi<{classified:number;failedBatches?:number;model:string;usage:{inputTokens:number;outputTokens:number}|null}>('classify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:true})});setNotice(`已分類 ${result.classified} 部影片${result.usage?`，${result.model}，輸入 ${result.usage.inputTokens}／輸出 ${result.usage.outputTokens} tokens。`:'。'}${result.failedBatches?`有 ${result.failedBatches} 批未完成，已保留成功結果，可稍後續做。`:''}`);setRevision(v=>v+1);}catch(err){setError((err as Error).message);setNotice('');}finally{setBusy(false);}}
  async function exportData(){setBusy(true);setError('');try{const response=await fetch(`/api/v1/media/export?part=${exportPart}`,{cache:'no-store',credentials:'same-origin'});if(!response.ok)throw new Error('匯出失敗，請稍後再試。');const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`zhiyu-media-${exportPart}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}
  async function clear(){setBusy(true);setError('');try{await mediaApi('clear',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:true})});setDeleting(false);setConfirmation('');setNotice('影音紀錄及分類已清除。');setRevision(v=>v+1);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}
  const move=(id:string,step:number)=>{if(!state)return;const widgets=[...state.widgets],index=widgets.indexOf(id),target=index+step;if(target<0||target>=widgets.length)return;[widgets[index],widgets[target]]=[widgets[target],widgets[index]];void update({...state,widgets});};
  const heading=(id:string)=><div className="media-card-heading"><h2>{names[id]}</h2>{editing&&<div><button className="icon-button" aria-label={`上移${names[id]}`} onClick={()=>move(id,-1)} disabled={state?.widgets[0]===id}><ArrowUp size={15}/></button><button className="icon-button" aria-label={`下移${names[id]}`} onClick={()=>move(id,1)} disabled={state?.widgets.at(-1)===id}><ArrowDown size={15}/></button></div>}</div>;
  const ranking=(items:MediaRanking[],compare=false)=><ol className="media-ranking">{items.slice(0,12).map((item,i)=><li key={item.name}><span className="media-rank-number">{i+1}</span><div><div className="media-rank-label"><strong>{item.name}</strong><span>{number(item.count)} 次 · {(item.share*100).toFixed(1)}%</span></div><div className="media-bar-track"><span style={{width:`${Math.min(100,item.share*100)}%`}}/></div>{compare&&range!=='all'&&<small>前一個同長度期間 {number(item.previousCount)} 次</small>}</div></li>)}</ol>;
  if(!state?.enabled)return <section className="card media-disabled"><Film size={36}/><h1>為在意的影音，留一個角落。</h1><p>啟用影音分析，連接 YouTube 擴充功能，讓觀看紀錄自動同步。</p><button className="button primary" onClick={openCatalog}>前往模組探索</button></section>;
  return <div className="media-page">
    <div className="page-intro"><div><span className="eyebrow">YOUR WATCHES, YOUR STORY</span><h1>看過的世界，慢慢成為你。</h1><p>由 urTube 延伸的私人影音分析 · 資料保存在你的知隅主機</p></div><div className="intro-actions"><button className="button secondary" disabled={busy} onClick={()=>setEditing(!editing)}>整理卡片</button><button className="button primary" disabled={busy} onClick={()=>upload.current?.click()}>{busy?<LoaderCircle className="spin" size={17}/>:<Upload size={17}/>}備份檔匯入</button></div></div>
    <MediaDevices onSync={()=>setRevision(v=>v+1)}/>
    <input ref={upload} type="file" accept=".zip,.json,.html" aria-label="匯入影音紀錄" className="media-file-input" onChange={event=>void importFile(event.target.files?.[0])}/>
    <div className="media-import-help"><details><summary>其他方式：匯入既有 urTube／Takeout 備份</summary><p>在 <a href="https://urtube.observe.tw/account" target="_blank" rel="noopener noreferrer">urTube Account</a> 匯出 ZIP；或在 <a href="https://takeout.google.com/" target="_blank" rel="noopener noreferrer">Google Takeout</a> 選擇 YouTube 觀看紀錄，下載 ZIP／watch-history.json／HTML 後匯入。也支援知隅自己匯出的 JSON。</p><p>每檔最多 50 MB、20 萬筆。只保存觀看資料及可沿用的主題分類；不匯入登入憑證、搜尋紀錄與交友關係。日常觀看請使用上方擴充功能自動同步；此處保留備份資料匯入。</p></details></div>
    <div className="media-toolbar"><div className="tabs" aria-label="影音分析期間">{ranges.map(([value,label])=><button key={value} className={range===value?'active':''} onClick={()=>setRange(value)}>{label}</button>)}</div><span>{summary?`已保存 ${number(summary.total)} 筆 · ${date(summary.from)} — ${date(summary.to)}`:'讀取資料中…'}</span></div>
    {editing&&<fieldset className="media-widget-picker"><legend>顯示卡片</legend>{Object.entries(names).map(([id,name])=><label key={id}><input type="checkbox" checked={state.widgets.includes(id)} onChange={event=>void update({...state,widgets:event.target.checked?[...state.widgets,id]:state.widgets.filter(v=>v!==id)})}/>{name}</label>)}</fieldset>}
    {error&&<p className="inline-error" role="alert">{error}</p>}{notice&&<p className="media-notice" role="status">{notice}</p>}
    {summary&&state.widgets.map(id=><section key={id} className={`card media-card media-${id}`}>{heading(id)}
      {id==='overview'&&<><div className="media-metrics"><div><small>觀看紀錄</small><strong>{number(summary.selected)}</strong><span>次</span></div><div><small>不同影片</small><strong>{number(summary.uniqueVideos)}</strong><span>部（可辨識 ID）</span></div><div><small>活躍日期</small><strong>{number(summary.activeDays)}</strong><span>天</span></div><MediaTimeMetric summary={summary}/></div><p className="media-note">歷史進度推估：{summary.progressEstimatedSeconds===null?'尚無資料':formatMediaDuration(summary.progressEstimatedSeconds)}（{number(summary.progressEvents)} 筆）。這是保存的播放位置／進度，每筆最多計 10 分鐘，無法還原每次實際看了多久；不併入實測時數。僅有片長 {number(summary.durationOnlyEvents)} 筆，不拿片長當觀看時間。另有 {number(Math.max(0,summary.selected-summary.estimatedEvents-summary.durationOnlyEvents))} 筆尚缺時間依據。</p>{summary.daily.length>0?<><h3>觀看分布（有紀錄{range==='all'||range==='365d'?'月份':'日期'}）</h3><div className="media-timeline" role="img" aria-label="各日期觀看次數">{summary.daily.slice(-90).map(item=><div key={item.date} title={`${item.date}：${item.count} 次`}><span style={{height:`${Math.max(2,item.count/Math.max(...summary.daily.map(d=>d.count))*100)}%`}}/></div>)}</div><div className="media-chart-label"><span>{summary.daily.slice(-90)[0]?.date}</span><span>{summary.daily.at(-1)?.date}</span></div></>:<p className="media-empty">這段期間沒有觀看紀錄，可切換至「全部紀錄」。</p>}</>}
      {id==='channels'&&<MediaChannels range={range} revision={revision}/>}
      {id==='topics'&&<><p className="media-note">此期間 {number(summary.classifiedEvents)}／{number(summary.selected)} 筆有主題。一部影片可有多個主題，占比加總可能超過 100%。分類描述影片內容，不代表你的身份或立場。</p>{summary.topics.length?ranking(summary.topics):<p className="media-empty">目前沒有可沿用的主題分類，可按需使用 AI 補充。</p>}<details className="media-ai"><summary>進階：逐部影片主題分類（選用）</summary><strong><Sparkles size={16}/> 補充分類</strong><p>按下後會將最多 {summary.aiBatchSize*summary.aiConcurrency} 部尚未分類影片（每批 {summary.aiBatchSize} 部、{summary.aiConcurrency} 批並行）的標題與頻道名稱送至 OpenAI GPT-5.6 Luna，不傳送觀看時間或帳號。結果保存在本機，不重複分類已有結果的影片。</p><button className="button secondary" disabled={busy||!summary.aiEnabled||!summary.unclassifiedVideos} onClick={()=>void classify()}>{busy?<LoaderCircle size={15} className="spin"/>:<Sparkles size={15}/>}並行分類（最多 {summary.aiBatchSize*summary.aiConcurrency} 部）</button><small>共 {number(summary.unclassifiedVideos)} 部待分類 · 與新聞分析共用全站每日次數上限</small></details></>}
      {id==='history'&&<><label className="search-input"><Search size={17}/><input placeholder="搜尋影片或頻道" aria-label="搜尋觀看紀錄" value={q} onChange={e=>setQ(e.target.value)}/></label><div className="media-history-list">{history.map(item=><article key={item.eventId}><div>{item.videoId?<a href={`https://www.youtube.com/watch?v=${item.videoId}`} target="_blank" rel="noopener noreferrer">{item.title} ↗</a>:<strong>{item.title}</strong>}<p>{item.channel??'未提供頻道'} · {item.precision==='day'?date(item.watchedAt):new Date(item.watchedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}{item.precision==='day'?'（僅日期）':''}</p><MediaWatchTime item={item}/><span className="media-topic-tags">{item.topics.map(topic=><span key={topic}>{topic}</span>)}</span>{item.topicSource&&<small>分類來源：{item.topicSource}</small>}</div></article>)}{!history.length&&<p className="media-empty">此條件下沒有觀看紀錄。</p>}</div><div className="media-pagination"><button className="button secondary" disabled={!page} onClick={()=>setPage(v=>v-1)}>上一頁</button><span>第 {page+1} 頁</span><button className="button secondary" disabled={!hasMore} onClick={()=>setPage(v=>v+1)}>下一頁</button></div></>}
    </section>)}
    {!state.widgets.length&&<p className="media-empty">點選「整理卡片」即可加入觀看概況、頻道、主題或紀錄。</p>}
    <section className="media-data-controls"><div><h3>你的紀錄，由你管理。</h3><p>跨裝置讀取相同的私人資料。停用模組會保留紀錄。</p>{summary?.imports.map(item=><small key={item.importedAt}>{item.source} · {date(item.importedAt)} · 新增 {number(item.inserted)} 筆</small>)}</div><div><button className="button secondary" disabled={busy} onClick={()=>void exportData()}><Download size={15}/>匯出影音資料</button>{(summary?.total??0)>5000&&<label>匯出分卷 <select aria-label="影音匯出分卷" value={exportPart} onChange={event=>setExportPart(Number(event.target.value))}>{Array.from({length:Math.ceil((summary?.total??0)/5000)},(_,i)=><option key={i+1} value={i+1}>第 {i+1} 卷（最多 5 千筆）</option>)}</select></label>}<button className="text-button" disabled={busy} onClick={()=>setDeleting(!deleting)}>清除影音資料</button></div></section>
    {deleting&&<div className="media-delete"><h3>清除這個帳號的影音紀錄與分類</h3><p>此操作會同時解除全部瀏覽器綁定，避免自動同步重新寫入。無法在網站內復原；可以先匯出保存。輸入「清除」以確認。</p><input aria-label="確認清除影音資料" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/><button className="button secondary" onClick={()=>setDeleting(false)}><X size={14}/>取消</button><button className="button primary" disabled={busy||confirmation!=='清除'} onClick={()=>void clear()}>確認清除</button></div>}
  </div>;
}
