import { useEffect,useState } from 'react';
import { Search,ChevronRight,X,Sparkles } from 'lucide-react';
import { CHANNEL_CATEGORIES,type ChannelOverview,type MediaChannel } from '../shared/media-channels';

const num=(n:number)=>n.toLocaleString('zh-TW');
const percent=(n:number,d:number)=>d?`${(100*n/d).toFixed(1)}%`:'—';
async function api<T>(path:string,body?:unknown):Promise<T>{
 const r=await fetch(`/api/v1/media/${path}`,{credentials:'same-origin',cache:'no-store',...(body===undefined?{}:{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});
 if(!r.headers.get('content-type')?.includes('application/json'))throw Error('主機暫時無法連線，已保留目前畫面。');
 const d=await r.json();if(!r.ok)throw Error(d.error??'讀取失敗');return d;
}
function ChannelAvatar({channel}:{channel:MediaChannel}){
 const [failed,setFailed]=useState(false);
 useEffect(()=>setFailed(false),[channel.iconUrl]);
 return <span className="channel-avatar">{channel.iconUrl&&!failed?<img src={channel.iconUrl} alt="" width={40} height={40} loading="lazy" decoding="async" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:Array.from(channel.name)[0]??'?'}</span>;
}
type Detail={videos:{id:string|null;title:string;count:number;first:string;last:string}[]};
export function MediaChannels({range,revision}:{range:string;revision:number}){
 const [data,setData]=useState<ChannelOverview|null>(null),[q,setQ]=useState(''),[category,setCategory]=useState(''),[page,setPage]=useState(0),[sort,setSort]=useState('count'),[local,setLocal]=useState(0);
 const [selected,setSelected]=useState<MediaChannel|null>(null),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[edit,setEdit]=useState('');
 useEffect(()=>{if(!selected)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};},[selected]);
 useEffect(()=>{setPage(0);setSelected(null);},[q,category,range,sort]);
 useEffect(()=>{let alive=true;const refresh=()=>void api<ChannelOverview>(`channels?range=${range}&q=${encodeURIComponent(q)}&category=${encodeURIComponent(category)}&page=${page}&sort=${sort}`).then(d=>{if(alive){setData(d);setError('');}}).catch(e=>{if(alive)setError(e.message);});const timer=window.setTimeout(refresh,250),poll=window.setInterval(refresh,30000);return()=>{alive=false;clearTimeout(timer);clearInterval(poll);};},[range,q,category,page,revision,local,sort]);
 useEffect(()=>{let alive=true;setDetail(null);if(selected)void api<Detail>(`channel?key=${encodeURIComponent(selected.key)}&range=${range}`).then(d=>{if(alive)setDetail(d);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[selected,range]);
 async function automate(enabled:boolean){setBusy(true);try{await api('channel-automation',{enabled,confirm:true});setConsent(false);setLocal(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function review(value:string|null){if(!selected)return;setBusy(true);try{await api('channel-category',{key:selected.key,category:value});setLocal(v=>v+1);setSelected(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="channel-explorer">
  <p className="media-note">探索頻道、內容分類與你實際看過的影片。分類占比以本期間全部觀看紀錄為分母，尚未辨識的頻道也計入。</p>
  {error&&<p className="inline-error" role="alert">{error}</p>}
  {data?<>
   <div className="channel-coverage"><div><small>這段期間的頻道</small><strong>{num(data.totalChannels)}</strong></div><div><small>頻道辨識率</small><strong>{percent(data.identified,data.selected)}</strong></div><div><small>內容分類覆蓋</small><strong>{percent(data.categorized,data.selected)}</strong></div></div>
   <div className="channel-processing" role="status"><span className="channel-status-dot"/><div><strong>{data.metadata.pending||data.metadata.errors?'正在補齊頻道資料':'頻道資料整理狀態'}</strong><p>已驗證 {num(data.metadata.ready)}／{num(data.metadata.total)} 部影片 · 待處理 {num(data.metadata.pending)} · 來源無法提供 {num(data.metadata.unavailable)}{data.metadata.errors?` · 暫時失敗 ${num(data.metadata.errors)}（稍後重試）`:''}</p><small>每輪最多 {data.metadata.batchSize} 部、{data.metadata.concurrency} 個並行請求 · 近十分鐘約 {data.metadata.perMinute.toFixed(1)} 部／分鐘{data.metadata.estimatedMinutes!==null&&data.metadata.estimatedMinutes>0?` · 目前清單約 ${(data.metadata.estimatedMinutes/60).toFixed(1)} 小時`:""}。新增紀錄或來源限流會改變預估；關閉頁面仍會繼續。</small></div></div>
   <div className="channel-category-filters" aria-label="頻道內容分類"><button className={!category?'active':''} onClick={()=>setCategory('')}>全部</button>{data.categories.map(c=><button key={c.name} className={category===c.name?'active':''} onClick={()=>setCategory(c.name)}>{c.name}<span>{percent(c.count,data.selected)}</span></button>)}</div>
   <label className="search-input"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜尋所有頻道" aria-label="搜尋所有頻道"/></label>
   <label className="channel-sort">頻道排序 <select aria-label="頻道排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="count">觀看次數</option><option value="time">觀看時數（含估算）</option></select></label><div className="channel-grid">{data.items.map((c,i)=><button className="channel-tile" key={c.key} onClick={()=>{setSelected(c);setEdit(c.category==='尚未分類'?'無法判斷':c.category);}}><ChannelAvatar channel={c}/><span className="channel-tile-main"><strong>{c.name}</strong><small>{num(c.count)} 次 · {num(c.videos)} 部影片{c.estimatedSeconds!==null?` · ${(c.estimatedSeconds/3600).toFixed(1)} 小時（含估算）`:''}</small><span className="channel-labels"><span>{c.category}</span>{c.curatorTags.map(t=><span key={t} className="curator-tag">來源標籤：{t}</span>)}</span><span className="channel-tile-share"><span style={{width:`${Math.min(100,c.share*100)}%`}}/></span><small>{percent(c.count,data.selected)}{c.reviewed?' · 已確認':c.confidence!==null?' · AI 建議':''}</small></span><ChevronRight size={15}/></button>)}</div>
   {!data.items.length&&<p className="media-empty">沒有符合條件的頻道。</p>}
   <div className="media-pagination"><button className="button secondary" disabled={!page} onClick={()=>setPage(p=>p-1)}>上一頁</button><span>第 {page+1} 頁</span><button className="button secondary" disabled={!data.hasMore} onClick={()=>setPage(p=>p+1)}>下一頁</button></div>
   <details className="channel-provenance"><summary>urTube 公開頻道標籤與資料來源</summary><p>沿用 urTube 的「新聞、個人社論、社論節目」定義，由 analysis.tw 維護。標籤描述頻道內容，不代表觀看者的立場；可與 AI 內容類別重疊。</p>{data.curator.available?<><ul>{data.curator.groups.map(g=><li key={g.name}>{g.name}：{num(g.count)} 次觀看（{percent(g.count,data.selected)}）</li>)}</ul><p>來源時間 {data.curator.sourceTime} · 版本 {data.curator.version} · 快取最長 6 小時</p></>:<p>分類來源暫時無法驗證，暫不顯示來源標籤。</p>}<a href="https://github.com/skyhong2002/urtube.observe.tw/blob/main/docs/channel-tag-policy.md" target="_blank" rel="noopener noreferrer">查看 urTube 分類政策 ↗</a><p>未列入這三份清單的頻道不表示沒有內容類別，可由下方 AI 補充。</p></details>
   <div className="media-ai"><strong><Sparkles size={16}/> 自動整理頻道分類</strong><p>{data.processing.autoClassify?'已啟用；新資料會自動排入分類，結果保存在本機。':'啟用一次後，背景自動分類新頻道，不需要一批一批按按鈕。'}</p><p>每頻道以最多 8 部跨月份影片標題為依據；信心不足 65% 或沒有可核對的引用時，標示「無法判斷」。</p><small>今日 {data.processing.dailyBatches}／{data.processing.dailyLimit} 批，每批最多 {data.processing.batchSize} 個頻道、最多 {data.processing.concurrency} 批並行（目前 {data.processing.activeBatches} 批）；同時受全站 AI 次數上限限制。{data.processing.lastSuccess?`最近完成：${new Date(data.processing.lastSuccess).toLocaleString('zh-TW')}`:''}</small>{data.processing.error&&<p>{data.processing.error}</p>}{data.processing.autoClassify?<button className="button secondary" disabled={busy} onClick={()=>void automate(false)}>暫停自動分類</button>:<button className="button secondary" onClick={()=>setConsent(!consent)}>啟用自動分類</button>}
    {consent&&<div className="channel-consent"><p>將公開影片標題與頻道名稱送到 OpenAI GPT-5.6 Luna，不傳送帳號、觀看日期或時長。會使用站長設定的 API 額度。可隨時暫停；分類不會推論你的身份或立場。</p><button className="button primary" disabled={busy} onClick={()=>void automate(true)}>同意並開始自動分類</button></div>}
   </div>
  </>:<p className="media-empty">正在讀取頻道資料…</p>}
  {selected&&<div className="channel-detail-backdrop" onClick={()=>setSelected(null)}><section className="channel-detail" role="dialog" aria-modal="true" aria-label={`${selected.name}的頻道分析`} onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setSelected(null);if(e.key==='Tab'){const nodes=[...e.currentTarget.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],select,input')],first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><button autoFocus className="icon-button channel-close" aria-label="關閉頻道分析" onClick={()=>setSelected(null)}><X size={20}/></button><span className="eyebrow">CHANNEL INSIGHTS</span><div className="channel-detail-heading"><ChannelAvatar channel={selected}/><h2>{selected.name}</h2></div><p>{num(selected.count)} 次觀看 · {num(selected.videos)} 部影片{selected.estimatedSeconds!==null?` · ${(selected.estimatedSeconds/3600).toFixed(1)} 小時（含估算）`:''} · 占本期間 {percent(selected.count,data?.selected??0)}</p>{selected.url&&<a href={selected.url} target="_blank" rel="noopener noreferrer">在 YouTube 開啟頻道 ↗</a>}
   <h3>分類與依據</h3><p><strong>{selected.category}</strong> · {selected.source}{selected.confidence!==null?` · 信心 ${(selected.confidence*100).toFixed(0)}%`:''}</p><p className="media-note">根據你保存的影片樣本描述內容，未必代表頻道全部作品。</p>{selected.evidence.map(e=><blockquote key={e.id}><a href={`https://www.youtube.com/watch?v=${e.id}`} target="_blank" rel="noopener noreferrer">{e.title}</a><p>引用：「{e.quote}」</p></blockquote>)}{selected.generatedAt&&<><label>確認或調整分類 <select value={edit} onChange={e=>setEdit(e.target.value)} aria-label="頻道分類">{CHANNEL_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><div className="channel-review-actions"><button className="button secondary" disabled={busy} onClick={()=>void review(edit)}>保存我的分類</button>{selected.reviewed&&<button className="text-button" disabled={busy} onClick={()=>void review(null)}>恢復 AI 原始建議</button>}</div></>}
   <h3>這段期間看過的影片</h3>{detail?<ol className="channel-detail-videos">{detail.videos.map((v,i)=><li key={v.id??i}>{v.id?<a href={`https://www.youtube.com/watch?v=${v.id}`} target="_blank" rel="noopener noreferrer">{v.title}</a>:v.title}<small>{v.count} 次 · 最近 {new Date(v.last).toLocaleDateString('zh-TW',{timeZone:'Asia/Taipei'})}</small></li>)}</ol>:<p>正在讀取…</p>}<p className="media-note">顯示觀看次數最多的 30 部影片。</p>
  </section></div>}
 </div>;
}
